export const MAX_SOURCE_BYTES = 2 * 1024 * 1024;
export const MAX_DOCUMENT_DEPTH = 64;
export const MAX_DOCUMENT_NODES = 50_000;
export const MAX_REF_HOPS = 32;
export const MAX_UNIQUE_REF_TARGETS = 4_096;
export const MAX_OPERATIONS = 1_000;
export const MAX_SOURCE_TEXT_CHARS = 8_192;
export const MAX_SCHEMA_NODES_PER_FRAGMENT = 5_000;
export const MAX_DIAGNOSTICS = 500;
